### PR TITLE
Add myself to reviewers

### PR DESCRIPTION
**Pull request by tashimi**
Hi! I'd like to be a reviewer, and was invited by TAG-CS (Josh Berkus and co) to participate.

Signed-off-by: Tasha <tasha.drew@gmail.com>

### CODE REVIEW

**Review by endocrimes — APPROVED** [review]
+1. Tasha is a former member of the kubernetes Code Of Conduct committee and would be a great addition to the wg.

**Comment by jberkus** [comment]
Appointed by TAG-CS by vote of the chairs and tech leads.

- Josh Berkus
- Dawn Foster
- Carolyn Van Slyck

**Review by cblecker — APPROVED** [review]

**Comment by jberkus** [comment]
FYI: Tasha was appointed by SIG-CS during the original call for reviewers, and was omitted from the initial repo due to a clerical error.  This is not a new appointment.

**Comment by dims** [comment]
welcome @tashimi

**Comment by tashimi** [comment]
Thank yooooou!! 🥳🥳🥳

**Pull request merged**
